#!/bin/bash

set -e

VERSION="1.0.1"
IMAGE_BACKEND="ghcr.io/whoshotu/dr-code-v2-backend:latest"
IMAGE_FRONTEND="ghcr.io/whoshotu/dr-code-v2-frontend:latest"
# Favicon: included in frontend image (frontend/public/favicon.svg, favicon.ico)
PORTS=(3001 8002 27017)
COMPOSE_FILE="docker-compose.yml"
GITHUB_REPO="whoshotu/DR.Code-v2"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
        echo "windows"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if grep -qEi "(Microsoft|WSL)" /proc/version 2>/dev/null; then
            echo "wsl"
        else
            echo "linux"
        fi
    else
        echo "unknown"
    fi
}

check_docker() {
    log_step "Checking Docker..."
    
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed."
        echo ""
        echo "Install Docker Desktop:"
        echo "  macOS:    https://docs.docker.com/desktop/install/mac-install/"
        echo "  Windows:  https://docs.docker.com/desktop/install/windows-install/"
        echo "  Linux:    https://docs.docker.com/desktop/install/linux-install/"
        exit 1
    fi
    
    DOCKER_COMPOSE=""
    if command -v docker compose &> /dev/null; then
        DOCKER_COMPOSE="docker compose"
    elif command -v docker-compose &> /dev/null; then
        DOCKER_COMPOSE="docker-compose"
    else
        log_error "Docker Compose is not installed."
        echo ""
        echo "Install Docker Compose:"
        echo "  https://docs.docker.com/compose/install/"
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running."
        echo ""
        echo "Start Docker Desktop and try again."
        exit 1
    fi
    
    log_info "Docker is ready ($DOCKER_COMPOSE)"
}

login_ghcr() {
    log_step "Logging into GitHub Container Registry..."
    
    if [ -n "$GITHUB_TOKEN" ]; then
        echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin 2>/dev/null && log_info "Logged into GHCR" || log_warn "GHCR login failed (images may still be public)"
    elif [ -n "$GITHUB_ACTOR" ] && [ "$GITHUB_ACTOR" != "unknown" ]; then
        log_warn "GITHUB_TOKEN not set - may not be able to pull private images"
    fi
}

check_ports() {
    log_step "Checking ports..."
    
    INUSE=()
    for PORT in "${PORTS[@]}"; do
        if command -v lsof &> /dev/null; then
            if lsof -i:$PORT &> /dev/null; then
                INUSE+=($PORT)
            fi
        elif command -v netstat &> /dev/null; then
            if netstat -tuln 2>/dev/null | grep -q ":$PORT "; then
                INUSE+=($PORT)
            fi
        fi
    done
    
    if [ ${#INUSE[@]} -gt 0 ]; then
        log_warn "Ports in use: ${INUSE[*]}"
        log_warn "Services may fail to start."
        echo ""
        read -p "Continue anyway? [y/N] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Cancelled."
            exit 0
        fi
    else
        log_info "All ports available"
    fi
}

create_config() {
    if [ ! -f ".env.docker" ]; then
        log_step "Creating configuration..."
        cat > .env.docker << 'EOF'
# DR.CODE-v2 Docker Configuration
# Auto-generated by install.sh

# MongoDB: Uses docker network (auto-discovered)
# MONGO_URL=mongodb://mongo:27017/drcode

# Ollama: Uses host.docker.internal to reach host machine
# OLLAMA_BASE_URL=http://host.docker.internal:11434
# OLLAMA_MODEL=codellama

# Database
DB_NAME=drcode

# CORS
CORS_ORIGINS=http://localhost:3001
EOF
        log_info "Configuration created: .env.docker"
    else
        log_info "Configuration already exists: .env.docker"
    fi
}

pull_images() {
    log_step "Pulling Docker images..."
    log_info "Backend:  $IMAGE_BACKEND"
    log_info "Frontend: $IMAGE_FRONTEND"
    
    if docker pull $IMAGE_BACKEND; then
        log_info "Backend image pulled"
    else
        log_error "Failed to pull backend image"
        log_info "Trying to build locally..."
        return 1
    fi
    
    if docker pull $IMAGE_FRONTEND; then
        log_info "Frontend image pulled"
    else
        log_error "Failed to pull frontend image"
        return 1
    fi
    
    log_info "All images ready"
}

start_services() {
    log_step "Starting services..."
    
    if command -v docker compose &> /dev/null; then
        docker compose up -d --pull missing
    else
        docker-compose up -d --pull missing
    fi
    
    log_step "Waiting for services to be healthy..."
    
    local retries=30
    while [ $retries -gt 0 ]; do
        if curl -s http://localhost:8002/api/health &> /dev/null; then
            log_info "Backend is healthy"
            return 0
        fi
        retries=$((retries - 1))
        sleep 2
    done
    
    log_warn "Backend health check timed out - may still be starting"
    return 0
}

stop_services() {
    log_step "Stopping services..."
    
    if command -v docker compose &> /dev/null; then
        docker compose down
    else
        docker-compose down
    fi
    
    log_info "Services stopped"
}

clean_services() {
    log_step "Removing services and volumes..."
    
    if command -v docker compose &> /dev/null; then
        docker compose down -v
    else
        docker-compose down -v
    fi
    
    log_info "All data removed"
}

show_status() {
    echo ""
    echo "=========================================="
    echo "  DR.CODE v2 Status"
    echo "=========================================="
    echo ""
    
    if command -v docker compose &> /dev/null; then
        docker compose ps
    else
        docker-compose ps
    fi
    
    echo ""
    echo "URLs:"
    echo "  Frontend: http://localhost:3001"
    echo "  Backend:  http://localhost:8002"
    echo "  API:      http://localhost:8002/api"
    echo ""
    
    if curl -s http://localhost:8002/api/health &> /dev/null; then
        echo -e "Status:    ${GREEN}Running${NC}"
    else
        echo -e "Status:    ${YELLOW}Starting or stopped${NC}"
    fi
    echo ""
}

show_help() {
    echo "DR.CODE v2 Installer v$VERSION"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  install   (default)  Install and start services"
    echo "  start              Start services"
    echo "  stop               Stop services"
    echo "  status             Show service status"
    echo "  update             Pull latest images and restart"
    echo "  clean              Stop and remove all data"
    echo "  help               Show this help"
    echo ""
    echo "Ports: 3001 (frontend), 8002 (backend), 27017 (mongodb)"
    echo ""
    echo "Environment:"
    echo "  GITHUB_TOKEN       Personal Access Token for private images (optional)"
}

case "${1:-install}" in
    install)
        check_docker
        login_ghcr
        check_ports
        create_config
        pull_images || exit 1
        start_services
        show_status
        log_info "Installation complete!"
        ;;
    start)
        check_docker
        start_services
        show_status
        ;;
    stop)
        stop_services
        ;;
    status)
        show_status
        ;;
    update)
        check_docker
        login_ghcr
        log_step "Pulling latest images..."
        docker pull $IMAGE_BACKEND || log_warn "Failed to pull latest backend"
        docker pull $IMAGE_FRONTEND || log_warn "Failed to pull latest frontend"
        stop_services
        start_services
        show_status
        log_info "Update complete!"
        ;;
    clean)
        clean_services
        log_info "All data removed"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
