$VERSION = "1.0.0"
$IMAGE_BACKEND = "ghcr.io/whoshotu/dr-code-v2-backend:latest"
$IMAGE_FRONTEND = "ghcr.io/whoshotu/dr-code-v2-frontend:latest"
$PORTS = @(3001, 8002, 27017)

function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }
function Write-Step { param($msg) Write-Host "[STEP] $msg" -ForegroundColor Cyan }

function Test-Docker {
    Write-Step "Checking Docker..."
    
    $docker = Get-Command docker -ErrorAction SilentlyContinue
    if (-not $docker) {
        Write-Error "Docker is not installed."
        Write-Host ""
        Write-Host "Install Docker Desktop:" -ForegroundColor Yellow
        Write-Host "  https://docs.docker.com/desktop/install/windows-install/"
        exit 1
    }
    
    try {
        docker info 2>$null | Out-Null
    } catch {
        Write-Error "Docker daemon is not running."
        Write-Host ""
        Write-Host "Start Docker Desktop and try again." -ForegroundColor Yellow
        exit 1
    }
    
    Write-Info "Docker is ready"
}

function Login-GHCR {
    Write-Step "Logging into GitHub Container Registry..."
    
    if ($env:GITHUB_TOKEN) {
        $env:GITHUB_TOKEN | docker login ghcr.io -u $env:GITHUB_ACTOR --password-stdin 2>$null
        if ($?) {
            Write-Info "Logged into GHCR"
        } else {
            Write-Warn "GHCR login failed (images may still be public)"
        }
    } elseif ($env:GITHUB_ACTOR -and $env:GITHUB_ACTOR -ne "unknown") {
        Write-Warn "GITHUB_TOKEN not set - may not be able to pull private images"
    }
}

function Test-Ports {
    Write-Step "Checking ports..."
    $inUse = @()
    
    foreach ($port in $PORTS) {
        $connection = Test-NetConnection -ComputerName localhost -Port $port -WarningAction SilentlyContinue -ErrorAction SilentlyContinue
        if ($connection.TcpTestSucceeded) {
            $inUse += $port
        }
    }
    
    if ($inUse.Count -gt 0) {
        Write-Warn "Ports in use: $($inUse -join ', ')"
        Write-Warn "Services may fail to start."
        Write-Host ""
        $response = Read-Host "Continue anyway? (y/N)"
        if ($response -ne "y" -and $response -ne "Y") {
            Write-Info "Cancelled."
            exit 0
        }
    } else {
        Write-Info "All ports available"
    }
}

function New-Config {
    if (-not (Test-Path ".env.docker")) {
        Write-Step "Creating configuration..."
        @"
# DR.CODE-v2 Docker Configuration
# Auto-generated by install.ps1

# MongoDB: Uses docker network (auto-discovered)
# MONGO_URL=mongodb://mongo:27017/drcode

# Ollama: Uses host.docker.internal to reach host machine
# OLLAMA_BASE_URL=http://host.docker.internal:11434
# OLLAMA_MODEL=codellama

# Database
DB_NAME=drcode

# CORS
CORS_ORIGINS=http://localhost:3001
"@ | Out-File -FilePath ".env.docker" -Encoding UTF8
        Write-Info "Configuration created: .env.docker"
    } else {
        Write-Info "Configuration already exists: .env.docker"
    }
}

function Pull-Images {
    Write-Step "Pulling Docker images..."
    Write-Info "Backend:  $IMAGE_BACKEND"
    Write-Info "Frontend: $IMAGE_FRONTEND"
    
    $success = $true
    
    docker pull $IMAGE_BACKEND 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Info "Backend image pulled"
    } else {
        Write-Error "Failed to pull backend image"
        $success = $false
    }
    
    docker pull $IMAGE_FRONTEND 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Info "Frontend image pulled"
    } else {
        Write-Error "Failed to pull frontend image"
        $success = $false
    }
    
    return $success
}

function Start-Services {
    Write-Step "Starting services..."
    
    docker compose up -d --pull missing 2>$null
    if ($LASTEXITCODE -ne 0) {
        docker-compose up -d --pull missing 2>$null
    }
    
    Write-Step "Waiting for services to be healthy..."
    
    $retries = 30
    while ($retries -gt 0) {
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:8002/api/health" -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) {
                Write-Info "Backend is healthy"
                return
            }
        } catch {}
        $retries--
        Start-Sleep -Seconds 2
    }
    
    Write-Warn "Backend health check timed out - may still be starting"
}

function Stop-Services {
    Write-Step "Stopping services..."
    docker compose down 2>$null
    if ($LASTEXITCODE -ne 0) {
        docker-compose down 2>$null
    }
    Write-Info "Services stopped"
}

function Show-Status {
    Write-Host ""
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host "  DR.CODE v2 Status" -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
    
    docker compose ps 2>$null
    if ($LASTEXITCODE -ne 0) {
        docker-compose ps 2>$null
    }
    
    Write-Host ""
    Write-Host "URLs:" -ForegroundColor Cyan
    Write-Host "  Frontend: http://localhost:3001"
    Write-Host "  Backend:  http://localhost:8002"
    Write-Host "  API:      http://localhost:8002/api"
    Write-Host ""
    
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:8002/api/health" -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            Write-Host "Status:    Running" -ForegroundColor Green
        } else {
            Write-Host "Status:    Starting or stopped" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "Status:    Starting or stopped" -ForegroundColor Yellow
    }
    Write-Host ""
}

function Update-Services {
    Test-Docker
    Login-GHCR
    
    Write-Step "Pulling latest images..."
    docker pull $IMAGE_BACKEND 2>$null
    docker pull $IMAGE_FRONTEND 2>$null
    
    Stop-Services
    Start-Services
    Show-Status
    Write-Info "Update complete!"
}

function Clear-Services {
    Write-Step "Removing services and volumes..."
    docker compose down -v 2>$null
    if ($LASTEXITCODE -ne 0) {
        docker-compose down -v 2>$null
    }
    Write-Info "All data removed"
}

function Show-Help {
    Write-Host "DR.CODE v2 Installer v$VERSION" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage: .\install.ps1 [command]" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Commands:" -ForegroundColor Cyan
    Write-Host "  install   (default)  Install and start services"
    Write-Host "  start              Start services"
    Write-Host "  stop               Stop services"
    Write-Host "  status             Show service status"
    Write-Host "  update             Pull latest images"
    Write-Host "  clean              Stop and remove all data"
    Write-Host "  help               Show this help"
    Write-Host ""
    Write-Host "Ports: 3001 (frontend), 8002 (backend), 27017 (mongodb)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Environment:" -ForegroundColor Gray
    Write-Host "  GITHUB_TOKEN       Personal Access Token for private images" -ForegroundColor Gray
}

$command = $args[0]
if (-not $command) { $command = "install" }

switch ($command.ToLower()) {
    "install" {
        Test-Docker
        Login-GHCR
        Test-Ports
        New-Config
        if (-not (Pull-Images)) { exit 1 }
        Start-Services
        Show-Status
        Write-Info "Installation complete!"
    }
    "start" {
        Test-Docker
        Start-Services
        Show-Status
    }
    "stop" {
        Stop-Services
    }
    "status" {
        Show-Status
    }
    "update" {
        Update-Services
    }
    "clean" {
        Clear-Services
    }
    "help" {
        Show-Help
    }
    default { Write-Error "Unknown command: $command"; Show-Help; exit 1 }
}
